name: Open Pull Request when an `auto-pr` is pushed
on:
  push:
    branches:
      - 'auto-pr/**'

jobs:
  open-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "open a pull request"
        id: open-pr
        run: |
          # this runs everytime the PR gets pushed too, whilst you can only create a PR a single time
          # so we should be smarter, but piping this to /dev/null is a fine workaround for MVP
          gh pr create --title "$PR_TITLE" --body "$PR_BODY" -B "$PR_TARGET" -l "$PR_LABEL" > /dev/null

        env:
          PR_TITLE: "Auto PR: Regenerating the Go SDK (${{ github.sha }})"
          PR_BODY: "Regenerating the SDK based on the latest changes"
          PR_TARGET: "main"
          PR_LABEL: "release-once-merged"
          GITHUB_TOKEN: ${{ secrets.SERVICE_ACCOUNT_GO_SDK_TOKEN }}
