name: "Pull Request Labeler"
on:
  pull_request_target:
    types:
      - opened # run once per PR to work around https://github.com/actions/labeler/issues/624 (avoid unwanted label removal)

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594 # v4.3.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"