---
name: Unit Tests
on:
  pull_request:
    types: ['opened', 'synchronize']

jobs:
  unit-test:
    runs-on: custom-linux-medium
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: ./.go-version

      - name: Run unit tests
        run: make test

# vim: set ts=2 sts=2 sw=2 et:
