---
name: Validate Go Get
on:
  pull_request:
    types: ['opened', 'synchronize']

jobs:
  validate-go-get:
    runs-on: custom-linux-medium
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: ./.go-version

      - name: "install tools / run unit tests"
        run: |
          ./scripts/validate-go-get.sh