---
name: Validate Go Get
on:
  pull_request:
    types: ['opened', 'synchronize']

jobs:
  validate-go-get:
    runs-on: custom-linux-medium
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: ./.go-version

      - name: "install tools / run unit tests"
        run: |
          ./scripts/validate-go-get.sh