---
name: Validate Go Get
on:
  pull_request:
    types: ['opened', 'synchronize']

jobs:
  validate-go-get:
    runs-on: custom-linux-medium
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: '1.19.5'

      - name: "install tools / run unit tests"
        run: |
          ./scripts/validate-go-get.sh