---
name: Validate Go Get
on:
  pull_request:
    types: ['opened', 'synchronize']

jobs:
  validate-go-get:
    runs-on: custom-linux-medium
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: ./.go-version

      - name: "install tools / run unit tests"
        run: |
          ./scripts/validate-go-get.sh